apiVersion: v1
kind: ConfigMap
metadata:
  name: devsu-api-config
data:
  APP_PORT: "8000"
  DATABASE_NAME: "db.sqlite3"
---
apiVersion: v1
kind: Secret
metadata:
  name: devsu-api-secrets
type: Opaque
data:
  DJANGO_SECRET_KEY: "ZGphbmdvLWV4YW0ta2V5LWZyZXNoLTIwMjY="
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsu-api-deployment
  labels:
    app: devsu-api
spec:
#Usando 2 replicas para alta disponibilidad
  replicas: 2
  selector:
    matchLabels:
      app: devsu-api
  template:
    metadata:
      labels:
        app: devsu-api
    spec:
      containers:
# Usando imagen del repositorio Dockerhub
      - name: devsu-api-container
        image: coshao/devsu-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: devsu-api-config
              key: APP_PORT
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: devsu-api-config
              key: DATABASE_NAME
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: devsu-api-secrets
              key: DJANGO_SECRET_KEY
# Estableciendo limites de recursos de cpu y ram
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: devsu-api-service
# Exponiendo el puerto para poder acceder desde el navegador web
spec:
  type: ClusterIP
  selector:
    app: devsu-api
  ports:
  - port: 8000
    targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devsu-api-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devsu-api-service
            port:
              number: 8000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devsu-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devsu-api-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50