apiVersion: v1
kind: ConfigMap
metadata:
  name: devsu-api-config
data:
  APP_PORT: "8000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsu-api-deployment
  labels:
    app: devsu-api
spec:
#Usando 3 replicas para alta disponibilidad
  replicas: 3
  selector:
    matchLabels:
      app: devsu-api
  template:
    metadata:
      labels:
        app: devsu-api
    spec:
      containers:
# Usando imagen del repositorio Dockerhub
      - name: devsu-api-container
        image: coshao/devsu-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: APP_PORT
          valueFrom:
          ConfigMapKeyRef:
            name: devsu-api-config
            key: APP_PORT
# Estableciendo limites de recursos de cpu y ram
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: devsu-api-service
# Exponiendo el puerto para poder acceder desde el navegador web
spec:
  type: LoadBalancer
  selector:
    app: devsu-api
  ports:
  - port: 8000
    targetPort: 8000
---
