name: Devsu Pipeline
on:
    push:
        branches: [ "main", "master"]
    pull_request: 
        branches: [ "main", "master"]
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout del codigo
              uses: actions/checkout@v3

            - name: Configuracion del python 3.11
              uses: actions/setup-python@v4
              with:
                python-version: '3.11.3'

            - name: Instalando dependencias
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install flake8 coverage
                
            - name: Analisis de Codigo Linting
              run: |
                flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

            - name: Ejecutando tests con cobertura
              env:
                DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
                DATABASE_NAME: "db.sqlite3"
              run: | 
                coverage run manage.py test
                coverage report -m

            - name: Logueandose en Docker hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Construyendo y subiendo la imagen a Docker hub
              run: |
                docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devsu-api:latest .
                docker push ${{ secrets.DOCKERHUB_USERNAME }}/devsu-api:latest
